name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Start Application
        run: npm start &
        
      - name: Wait for App
        run: npx wait-on http://localhost:3000
        
      - name: Cypress run
        uses: cypress-io/github-action@v7
